---
title: "Snow Data Assignment: Web Scraping, Functions, and Iteration"
author: "Casey Menick"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
---
# Data Import

## Import Libraries
```{r, message=FALSE, warning=FALSE}
library(rvest)
library(tidyverse)
library(lubridate)
library(readxl)
library(dataRetrieval)
library(dygraphs)
library(xts)
library(magrittr)
```

## Locate Data

```{r}
# read in html
site_url <- 'https://snowstudies.org/archived-data/'
webpage <- read_html(site_url)

# locate tables within htrml
tables <- webpage %>%
  html_nodes('table') %>%
  extract2(3) %>%
  html_table(fill=TRUE)

# locate data links
links <- webpage %>%
  html_nodes('a') %>%
  .[grepl('forcing',.)] %>%
  html_attr('href')
```

## Download Data

```{r, message=FALSE, warning=FALSE}
# select appropriate links
splits <- str_split_fixed(links,'/',8)

# keep only the 8th column
dataset <- splits[,8] 

# generate a file list for where the data goes
file_names <- paste0('data/',dataset)

# create for loop to download files of interest
for(i in 1:length(file_names)){
  download.file(links[i],destfile=file_names[i])
}

# confirm data has downloaded
downloaded <- file.exists(file_names)
downloaded
```

## Read in data

```{r, message=FALSE, warning=FALSE}

# grab the variable names from the metadata pdf file
library(pdftools)
headers <- pdf_text('https://snowstudies.org/wp-content/uploads/2022/02/Serially-Complete-Metadata-text08.pdf') %>%
  readr::read_lines(.) %>%
  trimws(.) %>%
  str_split_fixed(.,'\\.',2) %>%
  .[,2] %>%
  .[1:26] %>%
  str_trim(side = "left")

# create function that takes the file names and a site column to read in txt file
forcing_reader <- function(file){
  read_table(file,col_names=headers,skip=4) %>%
    select(1:14) %>%
    mutate(site = substr(file,10,11))
}

# read in data with map and created function
forcing_list <- map(file_names,forcing_reader)
forcing_full <- do.call("rbind", forcing_list)
summary(forcing_full)

```
# Data Analysis

## Mean Temperature Over Time

### Yearly

```{r, message=FALSE, warning=FALSE}
# create plot showing average temperature for each year between the two sites
ggplot(forcing_full %>%
         filter(!is.na(.),
         year %in% 2005:2010) %>%
         group_by(year,site) %>%
         summarize(airtemp = mean(`air temp [K]`)), aes(year, airtemp, color=site)) +
  geom_line() +
  scale_x_continuous(breaks=2005:2011) +
  xlab("Year") +
  ylab("Air Temperature (K)") +
  labs(title = "Annual Mean Temperature for Snow Angel and Senator Beck Study Plots")
```

### Monthly, Across Years

```{r, message=FALSE, warning=FALSE}

# create function to group and then plot data
precip_plotter <- function(data,singleyear){
  data <- data %>%
    group_by(site,month,year) %>%
    summarize(temp = mean(`air temp [K]`)) %>%
    filter(year==singleyear)
  ggplot(data,aes(month,temp,color=site)) +
    geom_line() +
    ggtitle("Montly Mean Temperature at Senator Beck and Snow Angel Study Plots") + 
    labs(subtitle= year) +
    xlab("Month") +
    ylab("Temperature (K)") + 
    scale_x_continuous(breaks=1:12)
}

# utilize function in for loop to graph precipitation data for 2005-2010
for(year in 2005:2010){
  x <- precip_plotter(forcing_full,year)
  print(x)
}
```

## Mean Precipitation Over Time

### By Day Number, Averaged

```{r, message=FALSE, warning=FALSE}
# create plot showing average precipitation for each day number for 2005-2010
ggplot(forcing_full %>%
         mutate(date = make_date(year, month, day),
                day_no = yday(date)) %>%
         group_by(site,day_no) %>%
         summarize(precip = mean(`precip [kg m-2 s-1]`)) %>%
         filter(!is.na(precip)), aes(day_no,precip)) +
  geom_point() +
  geom_smooth() +
  labs(title="Daily Mean Precipitation for Snow Angel and Senator Beck Study Plots", subtitle = "2005-2010") +
  xlab("Day Number") + 
  ylab("Precipitation (kg m-2 s-1)")
```

### By Day Number, 2005-2010

```{r, message=FALSE, warning=FALSE}
# create function to plot precipitation by day number for any given year
precip_plotter_day <- function(data, singleyear){
  ggplot(data %>%
         mutate(date = make_date(year, month, day),
                day_no = yday(date)) %>%
         group_by(site,day_no,year) %>%
         summarize(precip = mean(`precip [kg m-2 s-1]`)) %>%
         filter(!is.na(precip),
                year == singleyear)
       , aes(day_no,precip)) +
  geom_point() + 
    geom_smooth()+
    xlab("Day Number") +
    ylab("Precipitation (kg m-2 s-1)") +
    labs(title = "Daily Mean Precipitation for Snow Angel and Senator Beck Study Plots",subtitle= singleyear)
}

# utilize for loop to plot data for 2005-2010
for(eachyear in 2005:2010){
  x <- precip_plotter_day(forcing_full,eachyear)
  print(x)
}
```
